#!/usr/bin/env python3
"""Writes a Mintlify copy of the documentation into mintlify/ at the repository root.

    python3 tools/site/mintlify.py      (build.py runs it too, after the site)

The pages of site/ stay the documentation readers use. The copy exists so that Mintlify's AI Q&A answers
questions from the same text: Mintlify reads docs.json and the .mdx pages of mintlify/ from the default branch
(dashboard: Git settings, "docs.json is in a subdirectory", path /mintlify). Every file in mintlify/ is generated;
edit tools/site/content/ and the strings, never mintlify/.

The screenshots are not copied: the pages show the published WebP copies of the documentation site, and each
picture's alt text (strings/<lang>.json "img") describes what it shows, which is what the AI Q&A reads.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build as B  # noqa: E402
from md import CALLOUT, FIGURE, HEADING, OL, SHORTCODE, UL, join_lines  # noqa: E402

OUT = os.path.join(B.ROOT, 'mintlify')
SITE = B.CONFIG['siteUrl']
REPO = B.CONFIG['repo']
# Mintlify's language codes for the four languages; the folders keep the site's codes
MINT_LANG = {'en': 'en', 'zh': 'cn', 'ja': 'jp', 'ko': 'ko'}
GENERATED = '{/* Generated by tools/site/mintlify.py from tools/site/content/. Edit the source, not this file. */}'
KIND = {'tip': 'Tip', 'warning': 'Warning', 'note': 'Note'}


def page_href(lang, slug, frag=''):
    path = '/%s' % lang if slug == 'index' else '/%s/%s' % (lang, slug)
    return path + ('#' + frag if frag else '')


def attr(text):
    """A value for a JSX attribute in double quotes."""
    return text.replace('&', '&amp;').replace('"', '&quot;')


def plain_inline(text):
    """The source's inline marks reduced to plain text (for attributes such as a caption)."""
    text = re.sub(r'\(\((.+?)\)\)', r'\1', text)
    text = re.sub(r'\[\[(.+?)\]\]', r'\1', text)
    text = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)', r'\1', text)
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'`([^`]+)`', r'\1', text)
    return text.replace('{adv}', '').strip()


class Page:
    def __init__(self, lang, slug, metas):
        self.lang, self.slug, self.metas = lang, slug, metas

    # ------------------------------------------------------------------------------------------------ inline
    def inline(self, text):
        keep = []

        def hold(s):
            keep.append(s)
            return '\x00%d\x00' % (len(keep) - 1)

        text = re.sub(r'`[^`]+`', lambda m: hold(m.group(0)), text)
        text = re.sub(r'\(\((.+?)\)\)', lambda m: hold('+'.join(
            '<kbd>%s</kbd>' % self.escape(p.strip()) for p in m.group(1).split('+') if p.strip())), text)
        text = re.sub(r'\[\[(.+?)\]\]', r'**\1**', text)
        text = text.replace('{adv}', hold('<sup>%s</sup>' % self.escape(B.S(self.lang, 'settings.advancedBadge'))))

        def link(m):
            url = m.group(2)
            if not re.match(r'^[a-z]+:', url):
                target, _, frag = url.partition('#')
                if target.endswith('.html') and target[:-5] in B.SLUGS:
                    url = page_href(self.lang, target[:-5], frag)
                elif not target and frag:
                    url = '#' + frag
                else:
                    url = SITE + url.lstrip('./')
            return '[%s](%s)' % (m.group(1), hold(url))

        text = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)', link, text)
        text = self.escape(text)
        while '\x00' in text:
            text = re.sub(r'\x00(\d+)\x00', lambda m: keep[int(m.group(1))], text)
        return text

    @staticmethod
    def escape(text):
        return text.replace('{', '\\{').replace('}', '\\}').replace('<', '&lt;')

    # ------------------------------------------------------------------------------------------------ blocks
    def starts_block(self, line):
        s = line.strip()
        return bool(HEADING.match(s) or s.startswith('```') or s.startswith('>') or s.startswith('=>') or
                    s.startswith('|') or OL.match(s) or UL.match(s) or FIGURE.match(s) or SHORTCODE.match(s))

    def convert(self, text):
        text = re.sub(r'<!--.*?-->', '', text, flags=re.S).replace('{root}', SITE)
        return self.lines(text.replace('\r\n', '\n').replace('\t', '    ').split('\n'))

    def lines(self, lines):
        out = []
        i, n = 0, len(lines)
        while i < n:
            line = lines[i]
            s = line.strip()
            ind = line[:len(line) - len(line.lstrip())]
            if not s:
                out.append('')
                i += 1
                continue
            if s.startswith('```'):
                out.append(line)
                i += 1
                while i < n and not lines[i].strip().startswith('```'):
                    out.append(lines[i])
                    i += 1
                if i < n:
                    out.append(lines[i])
                    i += 1
                continue
            m = HEADING.match(s)
            if m and not ind:
                out.append('%s %s' % (m.group(1), self.inline(m.group(2))))
                i += 1
                continue
            m = FIGURE.match(s)
            if m:
                out.extend(self.figure(ind, m.group(2), m.group(1), m.group(3) or ''))
                i += 1
                continue
            m = SHORTCODE.match(s)
            if m:
                out.extend(ind + x if x else '' for x in self.shortcode(m.group(1), m.group(2)))
                i += 1
                continue
            if s.startswith('>'):
                body = []
                while i < n and lines[i].strip().startswith('>'):
                    body.append(re.sub(r'^\s*>\s?', '', lines[i]))
                    i += 1
                c = CALLOUT.match(body[0].strip())
                if c:
                    tag = KIND[c.group(1).lower()]
                    inner = ['**%s**' % self.inline(c.group(2).strip()), ''] if c.group(2).strip() else []
                    inner += self.lines(body[1:])
                    out += ['', ind + '<%s>' % tag, ''] + [ind + x if x else '' for x in inner] + ['', ind + '</%s>' % tag, '']
                else:
                    out += [ind + '> ' + x if x else ind + '>' for x in self.lines(body)]
                continue
            if s.startswith('=>'):
                body = [s[2:].strip()]
                i += 1
                while i < n and lines[i].strip() and not self.starts_block(lines[i]):
                    body.append(lines[i].strip())
                    i += 1
                out += ['', ind + '<Check>%s</Check>' % self.inline(join_lines(body)), '']
                continue
            if s.startswith('|'):
                if re.match(r'^\|?\s*:?-{2,}', s):
                    out.append(line)
                else:
                    row = re.sub(r'^(\|[^|]*?)\s*\{#[A-Za-z0-9_-]+\}\s*\|', r'\1 |', s, count=1)
                    out.append(ind + self.inline(row))
                i += 1
                continue
            out.append(ind + self.inline(s))
            i += 1
        # no more than one empty line in a row
        tidy = []
        for x in out:
            if x.strip() or (tidy and tidy[-1].strip()):
                tidy.append(x.rstrip())
        return tidy

    # ------------------------------------------------------------------------------------------------ pictures
    def figure(self, ind, name, alt, caption):
        if name not in B.IMAGES:
            return []
        gen = os.path.join(B.OUT, 'assets', 'img', 'gen')
        sub = self.lang + '/' if self.lang != 'en' and os.path.exists(os.path.join(gen, self.lang, name + '.webp')) else ''
        info_path = os.path.join(gen, sub, name + '.json')
        if not os.path.exists(info_path):
            return []
        info = json.loads(B.read(info_path))
        opt = B.image_options(name, self.lang if sub else 'en')
        alt = alt or B.S(self.lang, 'img.' + name)
        width = ''
        if opt.get('look') == 'panel':
            width = ' width="%d"' % min(opt.get('show', info['w']), info['w'])
        src = '%sassets/img/gen/%s%s' % (SITE, sub, name)
        cap = ' caption="%s"' % attr(plain_inline(caption)) if caption else ''
        if os.path.exists(os.path.join(gen, sub, name + B.LIGHT + '.json')):   # a twin in the light theme: Mintlify's own switch
            imgs = ['<img className="block dark:hidden" src="%s%s.webp" alt="%s"%s />' % (src, B.LIGHT, attr(alt), width),
                    '<img className="hidden dark:block" src="%s.webp" alt="%s"%s />' % (src, attr(alt), width)]
        else:
            imgs = ['<img src="%s.webp" alt="%s"%s />' % (src, attr(alt), width)]
        return ['', ind + '<Frame%s>' % cap] + [ind + '  ' + i for i in imgs] + [ind + '</Frame>', '']

    # ------------------------------------------------------------------------------------------------ shortcodes
    def shortcode(self, name, arg):
        S = lambda key, **k: B.S(self.lang, key, **k)  # noqa: E731
        if name == 'diagram':
            label, nodes = B.DIAGRAMS[arg]
            out = ['', '**%s**' % self.escape(S(label)), '']
            for k, nd in enumerate(nodes, 1):
                line = '%d. **%s**' % (k, self.escape(S(nd['t'])))
                if nd.get('s'):
                    line += ': ' + self.escape(S(nd['s']))
                if nd.get('optional'):
                    line += ' (%s)' % self.escape(S('diagram.pipeOptional'))
                if nd.get('takes'):
                    line += ' %s: %s' % (self.escape(S('diagram.pipeTakes')), ', '.join(self.escape(S(t)) for t in nd['takes']))
                out.append(line)
            return out + ['']
        if name == 'wipe':
            # the draggable illustration lives on the documentation site: link to it there
            d = next(L['dir'] for L in B.LANGS if L['code'] == self.lang)
            url = '%s%s%s.html' % (SITE, d + '/' if d else '', self.slug)
            return ['', '[%s](%s)' % (self.escape(B.S(self.lang, 'wipe.label')), url), '']
        if name == 'downloads':
            d = B.CONFIG['downloads']
            out = ['', '<CardGroup cols={3}>']
            for key, more in (('geforce', 'install'), ('radeon', 'radeon'), ('linux', 'linux')):
                url = '%s/releases/latest/download/%s' % (REPO, d[key])
                out += ['  <Card title="%s" icon="download" href="%s">' % (attr(S('downloads.%sTitle' % key)), url),
                        '    %s' % self.escape(S('downloads.%sCards' % key)), '',
                        '    %s' % self.escape(S('downloads.%sNote' % key)), '',
                        '    `%s` · [%s](%s)' % (d[key], self.escape(S('downloads.more')), page_href(self.lang, more)),
                        '  </Card>']
            out += ['</CardGroup>', '', '[%s](%s/releases)' % (self.escape(S('home.allReleases')), REPO), '']
            return out
        if name == 'tree':
            groups = [
                ('tree.programTitle', 'tree.programSub', 'VRChatDLSS5Cam-win64\\', [
                    ('VRChatDLSS5Cam.exe', 'tree.exe'), ('runtimes\\', 'tree.runtimes'), ('models\\', 'tree.models'),
                    ('licenses\\', 'tree.licenses'), ('docs\\', 'tree.docs'), ('README.md', 'tree.readme')]),
                ('tree.settingsTitle', 'tree.settingsSub', '%LOCALAPPDATA%\\VRChatDLSS5Cam\\', [
                    ('settings.ini', 'tree.settingsIni'), ('presets.txt', 'tree.presetsTxt'),
                    ('log.txt, log-1.txt … log-5.txt', 'tree.logTxt'), ('log-crash.txt, crash.txt', 'tree.crashTxt')]),
                ('tree.picturesTitle', 'tree.picturesSub', 'Pictures\\VRChat DLSS5 Cam\\', [
                    ('*.png, *.mp4, *.webp …', 'tree.pictures')]),
            ]
            out = ['']
            for title, sub, path, rows in groups:
                out += ['**%s** (%s): `%s`' % (self.escape(S(title)), self.escape(S(sub)), path), '']
                out += ['- `%s`: %s' % (f, self.escape(S(desc))) for f, desc in rows]
                out.append('')
            return out
        if name == 'pagelist':
            pages = [p for p in B.PAGES if p['section'] == arg and p['slug'] != 'index']
            out = ['', '<CardGroup cols={2}>']
            for p in pages:
                m = self.metas[p['slug']]
                out += ['  <Card title="%s" icon="%s" href="%s">' % (attr(m['nav']), p['icon'], page_href(self.lang, p['slug'])),
                        '    %s' % self.escape(m.get('description', '')), '  </Card>']
            return out + ['</CardGroup>', '']
        if name == 'changelog':
            return self.convert(B.changelog_md(self.lang))
        return []


def front(meta, page):
    rows = [('title', meta.get('title', page['slug'])), ('sidebarTitle', meta.get('nav', '')),
            ('description', meta.get('description', '')), ('icon', page.get('icon', ''))]
    return '---\n%s\n---\n' % '\n'.join('%s: %s' % (k, json.dumps(v, ensure_ascii=False)) for k, v in rows if v)


def docs_json():
    langs = []
    for L in B.LANGS:
        code = L['code']
        groups = []
        for sec in B.CONFIG['sections']:
            groups.append({'group': B.S(code, 'nav.' + sec['id']),
                           'pages': ['%s/%s' % (code, p['slug']) for p in sec['pages']]})
        langs.append({'language': MINT_LANG[code], 'groups': groups})
    return {
        '$schema': 'https://mintlify.com/docs.json',
        'theme': 'mint',
        'name': B.CONFIG['name'],
        'description': B.load_page('en', 'index')[0].get('description', ''),
        'colors': {'primary': '#4658E6', 'light': '#7281FF', 'dark': '#4658E6'},
        'favicon': '/favicon.svg',
        'icons': {'library': 'lucide'},
        'appearance': {'default': 'system'},
        'navbar': {'primary': {'type': 'github', 'href': REPO}},
        'footer': {'socials': {'github': REPO, 'website': SITE}},
        # The documentation site is the one search engines should list; this copy serves the AI Q&A.
        'seo': {'metatags': {'robots': 'noindex'}},
        'navigation': {'languages': langs},
    }


def export():
    written = set()
    for L in B.LANGS:
        code = L['code']
        metas = {p['slug']: B.load_page(code, p['slug'])[0] for p in B.PAGES}
        for page in B.PAGES:
            meta, text = B.load_page(code, page['slug'])
            body = '\n'.join(Page(code, page['slug'], metas).convert(text)).strip('\n')
            path = os.path.join(OUT, code, page['slug'] + '.mdx')
            B.write(path, front(meta, page) + '\n' + GENERATED + '\n\n' + body + '\n')
            written.add(os.path.normpath(path))
        # pages that no longer exist in site.json
        ldir = os.path.join(OUT, code)
        for f in os.listdir(ldir):
            full = os.path.normpath(os.path.join(ldir, f))
            if f.endswith('.mdx') and full not in written:
                os.remove(full)
    B.write(os.path.join(OUT, 'docs.json'), json.dumps(docs_json(), ensure_ascii=False, indent=2) + '\n')
    B.write(os.path.join(OUT, 'favicon.svg'), B.read(os.path.join(HERE, 'assets', 'logo.svg')))
    return len(written)


if __name__ == '__main__':
    n = export()
    print('wrote %d Mintlify pages into %s' % (n, os.path.relpath(OUT, B.ROOT)))
