#!/usr/bin/env python3
"""Builds src/ui/IconFont.h and IconFont.inc: the Lucide icon font (ISC licence) cut down to the glyphs the interface draws.

    npm pack lucide-static        (or download the tarball from the npm registry) and unpack it
    python3 tools/make_icon_font.py path/to/package/font

Needs fontTools. Add a name to GLYPHS, run the script again and use the constant it writes (lucide::name_with_underscores).
"""
import json
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

GLYPHS = [
    "chevron-down", "chevron-up", "chevron-left", "chevron-right", "rotate-ccw", "refresh-cw", "external-link", "x",
    "lock", "undo-2", "redo-2", "maximize", "minimize", "history", "circle-question-mark", "save", "pencil", "plus",
    "search", "rotate-ccw-square", "rotate-cw-square", "flip-horizontal-2", "flip-vertical-2", "crop", "image", "film",
    "radio", "sparkles", "download", "layers", "grid-2x2", "eye", "plug", "gauge", "info", "folder-open", "check",
    "camera", "triangle-alert", "sliders-horizontal", "circle-check", "circle-x", "image-plus", "languages", "trash-2",
    "keyboard", "monitor", "wand-sparkles", "settings", "columns-2", "zoom-in", "zoom-out", "terminal", "key-round",
    "upload", "copy", "images", "video", "cpu", "loader-circle", "import", "minus", "ellipsis", "list-checks",
    "square-check", "arrow-right", "sun", "moon", "bell", "scissors", "flag", "repeat", "file-image", "file-video",
    "mouse", "hand", "move", "focus", "aperture", "shield-check", "wifi", "hard-drive", "panel-left", "panel-right",
]


# Names that would read as C++ keywords (or the module "import") get a trailing underscore.
RESERVED = {"import", "export", "module", "delete", "new", "default", "switch", "case", "class", "private", "public"}


def CName(glyph):
    name = glyph.replace("-", "_")
    return name + "_" if name in RESERVED else name


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "package/font"
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    codepoints = json.load(open(os.path.join(src, "codepoints.json"), encoding="utf-8"))
    missing = [g for g in GLYPHS if g not in codepoints]
    if missing:
        sys.exit("not in this Lucide build: " + ", ".join(missing))

    font = TTFont(os.path.join(src, "lucide.ttf"))
    options = subset.Options()
    options.layout_features = []
    options.hinting = False
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
    options.notdef_outline = False
    options.glyph_names = False
    sub = subset.Subsetter(options)
    sub.populate(unicodes=[codepoints[g] for g in GLYPHS])
    sub.subset(font)
    out_ttf = os.path.join(src, "lucide-subset.ttf")
    font.save(out_ttf)
    data = open(out_ttf, "rb").read()

    head = [
        "// Lucide icons (https://lucide.dev, ISC licence - see THIRD_PARTY_NOTICES.md): the code points of the glyphs",
        "// in IconFont.inc. Generated by tools/make_icon_font.py; do not edit.",
        "#pragma once",
        "#include \"imgui.h\"",
        "",
        "namespace lucide {",
    ]
    for g in GLYPHS:
        head.append("constexpr ImWchar %s = 0x%04X;" % (CName(g), codepoints[g]))
    head.append("}")
    head.append("")
    data_lines = [
        "// Lucide icons (https://lucide.dev, ISC licence - see THIRD_PARTY_NOTICES.md), cut down to the glyphs the",
        "// interface draws (their code points are in IconFont.h). Generated by tools/make_icon_font.py; do not edit.",
        "alignas(4) static const unsigned char kIconFontData[%d] = {" % len(data),
    ]
    for i in range(0, len(data), 24):
        data_lines.append("    " + ",".join("0x%02x" % b for b in data[i:i + 24]) + ",")
    data_lines.append("};")
    data_lines.append("")
    ui = os.path.join(root, "src", "ui")
    for name, body in (("IconFont.h", head), ("IconFont.inc", data_lines)):
        with open(os.path.join(ui, name), "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(body))
    path = os.path.join(ui, "IconFont.inc")
    print("%s: %d glyphs, %d bytes" % (path, len(GLYPHS), len(data)))


if __name__ == "__main__":
    main()
